version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - appnet
    volumes:
      - ./vivero.db:/app/vivero.db  # Mapea el archivo SQLite a tu máquina local
    environment:
      SPRING_PROFILES_ACTIVE: "prod"

networks:
  appnet:
    driver: bridge
